package com.qqd.edicria.entities.enums;

import lombok.Getter;

@Getter
public enum EnumPaises {

    AFEGANISTAO("Afeganistão"),
    AFRICA_DO_SUL("África do Sul"),
    ALBANIA("Albânia"),
    ALEMANHA("Alemanha"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANTIGUA_E_BARBUDA("Antígua e Barbuda"),
    ARABIA_SAUDITA("Arábia Saudita"),
    ARGELIA("Argélia"),
    ARGENTINA("Argentina"),
    ARMENIA("Armênia"),
    AUSTRALIA("Austrália"),
    AUSTRIA("Áustria"),
    AZERBAIJAO("Azerbaijão"),

    BAHAMAS("Bahamas"),
    BAHREIN("Bahrein"),
    BANGLADESH("Bangladesh"),
    BARBADOS("Barbados"),
    BELARUS("Belarus"),
    BELGICA("Bélgica"),
    BELIZE("Belize"),
    BENIN("Benin"),
    BUTAO("Butão"),
    BOLIVIA("Bolívia"),
    BOSNIA_E_HERZEGOVINA("Bósnia e Herzegovina"),
    BOTSUANA("Botsuana"),
    BRASIL("Brasil"),
    BRUNEI("Brunei"),
    BULGARIA("Bulgária"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),

    CABO_VERDE("Cabo Verde"),
    CAMBOJA("Camboja"),
    CAMAROES("Camarões"),
    CANADA("Canadá"),
    CATAR("Catar"),
    CAZAQUISTAO("Cazaquistão"),
    CHADE("Chade"),
    CHILE("Chile"),
    CHINA("China"),
    CHIPRE("Chipre"),
    COLOMBIA("Colômbia"),
    COMORES("Comores"),
    CONGO("Congo"),
    COREIA_DO_NORTE("Coreia do Norte"),
    COREIA_DO_SUL("Coreia do Sul"),
    COSTA_DO_MARFIM("Costa do Marfim"),
    COSTA_RICA("Costa Rica"),
    CROACIA("Croácia"),
    CUBA("Cuba"),

    DINAMARCA("Dinamarca"),
    DJIBUTI("Djibuti"),
    DOMINICA("Dominica"),
    EGITO("Egito"),
    EL_SALVADOR("El Salvador"),
    EMIRADOS_ARABES_UNIDOS("Emirados Árabes Unidos"),
    EQUADOR("Equador"),
    ERITREIA("Eritreia"),
    ESLOVAQUIA("Eslováquia"),
    ESLOVENIA("Eslovênia"),
    ESPANHA("Espanha"),
    ESTADOS_UNIDOS("Estados Unidos"),
    ESTONIA("Estônia"),
    ESWATINI("Essuatíni"),
    ETIOPIA("Etiópia"),

    FIJI("Fiji"),
    FILIPINAS("Filipinas"),
    FINLANDIA("Finlândia"),
    FRANCA("França"),

    GABAO("Gabão"),
    GAMBIA("Gâmbia"),
    GANA("Gana"),
    GEORGIA("Geórgia"),
    GRANADA("Granada"),
    GRECIA("Grécia"),
    GUATEMALA("Guatemala"),
    GUIANA("Guiana"),
    GUINE("Guiné"),
    GUINE_BISSAU("Guiné-Bissau"),
    GUINE_EQUATORIAL("Guiné Equatorial"),

    HAITI("Haiti"),
    HONDURAS("Honduras"),
    HUNGRIA("Hungria"),

    IEMEN("Iêmen"),
    ILHAS_MARSHALL("Ilhas Marshall"),
    ILHAS_SALOMAO("Ilhas Salomão"),
    INDIA("Índia"),
    INDONESIA("Indonésia"),
    IRA("Irã"),
    IRAQUE("Iraque"),
    IRLANDA("Irlanda"),
    ISLANDIA("Islândia"),
    ISRAEL("Israel"),
    ITALIA("Itália"),

    JAMAICA("Jamaica"),
    JAPAO("Japão"),
    JORDANIA("Jordânia"),

    KIRIBATI("Kiribati"),
    KUWAIT("Kuwait"),

    LAOS("Laos"),
    LESOTO("Lesoto"),
    LETONIA("Letônia"),
    LIBANO("Líbano"),
    LIBERIA("Libéria"),
    LIBIA("Líbia"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIA("Lituânia"),
    LUXEMBURGO("Luxemburgo"),

    MACEDONIA_DO_NORTE("Macedônia do Norte"),
    MADAGASCAR("Madagascar"),
    MALASIA("Malásia"),
    MALAWI("Malawi"),
    MALDIVAS("Maldivas"),
    MALI("Mali"),
    MALTA("Malta"),
    MARROCOS("Marrocos"),
    MAURICIO("Maurício"),
    MAURITANIA("Mauritânia"),
    MEXICO("México"),
    MICO("Micronésia"),
    MOLDAVIA("Moldávia"),
    MONACO("Mônaco"),
    MONGOLIA("Mongólia"),
    MONTENEGRO("Montenegro"),
    MOCAMBIQUE("Moçambique"),
    MYANMAR("Myanmar"),

    NAMIBIA("Namíbia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NICARAGUA("Nicarágua"),
    NIGER("Níger"),
    NIGERIA("Nigéria"),
    NORUEGA("Noruega"),
    NOVA_ZELANDIA("Nova Zelândia"),

    OMA("Omã"),

    PAISES_BAIXOS("Países Baixos"),
    PALAU("Palau"),
    PALESTINA("Palestina"),
    PANAMA("Panamá"),
    PAPUA_NOVA_GUINE("Papua-Nova Guiné"),
    PAQUISTAO("Paquistão"),
    PARAGUAI("Paraguai"),
    PERU("Peru"),
    POLONIA("Polônia"),
    PORTUGAL("Portugal"),

    QUENIA("Quênia"),
    QUIRGUISTAO("Quirguistão"),

    REINO_UNIDO("Reino Unido"),
    REPUBLICA_CENTRO_AFRICANA("República Centro-Africana"),
    REPUBLICA_DEMOCRATICA_DO_CONGO("República Democrática do Congo"),
    REPUBLICA_DOMINICANA("República Dominicana"),
    REPUBLICA_TCHECA("República Tcheca"),
    ROMENIA("Romênia"),
    RUANDA("Ruanda"),
    RUSSIA("Rússia"),

    SAMOA("Samoa"),
    SAN_MARINO("San Marino"),
    SANTA_LUCIA("Santa Lúcia"),
    SAO_CRISTOVAO_E_NEVIS("São Cristóvão e Névis"),
    SAO_TOME_E_PRINCIPE("São Tomé e Príncipe"),
    SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas"),
    SEICHELES("Seicheles"),
    SENEGAL("Senegal"),
    SERRA_LEOA("Serra Leoa"),
    SERVIA("Sérvia"),
    SINGAPURA("Singapura"),
    SIRIA("Síria"),
    SOMALIA("Somália"),
    SRI_LANKA("Sri Lanka"),
    SUDAO("Sudão"),
    SUDAO_DO_SUL("Sudão do Sul"),
    SURINAME("Suriname"),
    SUECIA("Suécia"),
    SUICA("Suíça"),

    TAILANDIA("Tailândia"),
    TAIWAN("Taiwan"),
    TAJIQUISTAO("Tajiquistão"),
    TANZANIA("Tanzânia"),
    TIMOR_LESTE("Timor-Leste"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINIDAD_E_TOBAGO("Trinidad e Tobago"),
    TUNISIA("Tunísia"),
    TURCOMENISTAO("Turcomenistão"),
    TURQUIA("Turquia"),
    TUVALU("Tuvalu"),

    UCRANIA("Ucrânia"),
    UGANDA("Uganda"),
    URUGUAI("Uruguai"),
    UZBEQUISTAO("Uzbequistão"),

    VANUATU("Vanuatu"),
    VATICANO("Vaticano"),
    VENEZUELA("Venezuela"),
    VIETNA("Vietnã"),

    ZAMBIA("Zâmbia"),
    ZIMBABUE("Zimbábue");

    private String descricao;

    EnumPaises(String descricao) {
        this.descricao = descricao;
    }
}